# Generated by Django 5.2.11 on 2026-02-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia', models.IntegerField(max_length=4)),
                ('programacion', models.DecimalField(decimal_places=10, max_digits=30)),
                ('ejecucion', models.DecimalField(decimal_places=True, max_digits=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programacion',
                'verbose_name_plural': 'Programaciones',
            },
        ),
        migrations.CreateModel(
            name='TiposDeBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_banco', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '1. Tipo de Banco',
                'verbose_name_plural': '1. Tipos de Banco',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpin', models.CharField(max_length=20)),
                ('nombre_proyecto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('programamacion', models.ManyToManyField(to='proyectos.programaciones')),
                ('tipo_de_banco', models.ManyToManyField(to='proyectos.tiposdebanco')),
            ],
            options={
                'verbose_name': '2. Proyecto',
                'verbose_name_plural': '2. Proyectos',
            },
        ),
    ]
