# Generated by Django 5.2.11 on 2026-02-11 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaciones',
            name='vigencia',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='programamacion',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='programamacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.programaciones'),
        ),
    ]
