# Generated by Django 5.2.11 on 2026-02-11 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_programaciones_vigencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='programamacion',
        ),
        migrations.AddField(
            model_name='programaciones',
            name='proyectos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos'),
        ),
    ]
