# Generated by Django 5.2.11 on 2026-02-11 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_remove_proyectos_programamacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mes',
                'verbose_name_plural': 'Meses',
            },
        ),
        migrations.AlterField(
            model_name='programaciones',
            name='vigencia',
            field=models.IntegerField(unique=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.meses')),
        ),
        migrations.AddField(
            model_name='programaciones',
            name='mes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.meses'),
        ),
    ]
