# Generated by Django 5.2.11 on 2026-02-11 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_meses_alter_programaciones_vigencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vigencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vigecia',
                'verbose_name_plural': 'Vigencias',
            },
        ),
        migrations.AlterField(
            model_name='programaciones',
            name='mes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.meses', unique=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.vigencias')),
        ),
        migrations.AlterField(
            model_name='programaciones',
            name='vigencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.vigencias'),
        ),
    ]
