# Generated by Django 5.2.11 on 2026-02-11 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_vigencias_alter_programaciones_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaciones',
            name='mes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.meses', unique_for_year=True),
        ),
        migrations.AlterField(
            model_name='programaciones',
            name='vigencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.vigencias', unique_for_month=True),
        ),
    ]
