# Generated by Django 5.2.11 on 2026-02-11 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_alter_programaciones_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaciones',
            name='vigencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.vigencias'),
        ),
        migrations.AddConstraint(
            model_name='programaciones',
            constraint=models.UniqueConstraint(fields=('vigencia', 'mes'), name='unique_vigencia_mes'),
        ),
    ]
