# Generated by Django 5.2.11 on 2026-02-12 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_alter_indicadormga_options_and_more'),
        ('proyectos', '0008_alter_programaciones_vigencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuentesFinanciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fuente_financiacion', models.CharField(max_length=30)),
                ('fuente_financiacion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('proyectos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos')),
                ('sector_mga', models.ManyToManyField(null=True, to='contenido.sectormga')),
            ],
            options={
                'verbose_name': 'Fuente de Finanacion',
                'verbose_name_plural': 'Fuentes de Financiacion',
                'constraints': [models.UniqueConstraint(fields=('codigo_fuente_financiacion', 'fuente_financiacion'), name='codigo_fuente_nombre_fuente')],
            },
        ),
    ]
