# Generated by Django 5.2.11 on 2026-02-12 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_alter_indicadormga_options_and_more'),
        ('proyectos', '0009_fuentesfinanciacion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fuentesfinanciacion',
            name='codigo_fuente_nombre_fuente',
        ),
        migrations.AddField(
            model_name='fuentesfinanciacion',
            name='valor',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='fuentesfinanciacion',
            name='vigencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.vigencias'),
        ),
        migrations.AddConstraint(
            model_name='fuentesfinanciacion',
            constraint=models.UniqueConstraint(fields=('codigo_fuente_financiacion', 'fuente_financiacion', 'vigencia'), name='codigo_fuente_nombre_fuente'),
        ),
    ]
