# Generated by Django 5.2.11 on 2026-02-12 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_alter_indicadormga_options_and_more'),
        ('proyectos', '0010_remove_fuentesfinanciacion_codigo_fuente_nombre_fuente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fuente_financiacion', models.CharField(max_length=30)),
                ('fuente_financiacion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuente de Finanacion',
                'verbose_name_plural': 'Fuentes de Financiacion',
            },
        ),
        migrations.RemoveConstraint(
            model_name='fuentesfinanciacion',
            name='codigo_fuente_nombre_fuente',
        ),
        migrations.RemoveField(
            model_name='fuentesfinanciacion',
            name='codigo_fuente_financiacion',
        ),
        migrations.AddConstraint(
            model_name='fuentes',
            constraint=models.UniqueConstraint(fields=('codigo_fuente_financiacion', 'fuente_financiacion'), name='codigo_fuente_nombre_fuente'),
        ),
        migrations.AlterField(
            model_name='fuentesfinanciacion',
            name='fuente_financiacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.fuentes'),
        ),
        migrations.AddConstraint(
            model_name='fuentesfinanciacion',
            constraint=models.UniqueConstraint(fields=('fuente_financiacion', 'vigencia'), name='fuente_vigencia'),
        ),
    ]
