# Generated by Django 5.2.11 on 2026-02-12 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_alter_indicadormga_options_and_more'),
        ('proyectos', '0011_fuentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.indicadormga'),
        ),
    ]
