# Generated by Django 5.2.11 on 2026-02-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_proyectos_meta'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='programaciones',
            name='unique_vigencia_mes',
        ),
        migrations.AddConstraint(
            model_name='programaciones',
            constraint=models.UniqueConstraint(fields=('vigencia', 'mes', 'proyectos'), name='unique_vigencia_mes'),
        ),
    ]
