# Generated by Django 5.2.11 on 2026-02-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_remove_programaciones_unique_vigencia_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meses',
            name='numero',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
