# Generated by Django 5.2.11 on 2026-02-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_meses_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectos',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='tiposdebanco',
            options={'verbose_name': 'Tipo de Banco', 'verbose_name_plural': 'Tipos de Banco'},
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'constraints': [models.UniqueConstraint(fields=('municipio',), name='municipio_unique')],
            },
        ),
        migrations.AddField(
            model_name='proyectos',
            name='municipios',
            field=models.ManyToManyField(to='proyectos.municipios'),
        ),
    ]
