# Generated by Django 5.2.11 on 2026-02-09 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='ProgramaMGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_mga', models.CharField(max_length=80)),
                ('codigo_programa_mga', models.CharField(max_length=4)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programa Metodologia General Ajustada',
                'verbose_name_plural': 'Programas Metodologia General Ajustada',
            },
        ),
        migrations.CreateModel(
            name='ProgramaPDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_pdd', models.CharField(max_length=80)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programa Plan de Desarrollo',
                'verbose_name_plural': 'Programas Plan de Desarrollo',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='LineaEstrategica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea_estrategica', models.CharField(max_length=80)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Linea Estrategica',
                'verbose_name_plural': 'Lineas Estrategicas',
                'indexes': [models.Index(fields=['fecha_creacion'], name='contenido_l_fecha_c_7fd5e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductoMGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_mga', models.CharField(max_length=80)),
                ('codigo_producto_mga', models.CharField(max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('programa_mga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.programamga')),
            ],
            options={
                'verbose_name': 'Producto Metodologia General Ajustada',
                'verbose_name_plural': 'Productos Metodologia General Ajustada',
            },
        ),
        migrations.CreateModel(
            name='SectorMGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_mga', models.CharField(max_length=80)),
                ('codigo_sector_mga', models.CharField(max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('programa_pdd', models.ManyToManyField(to='contenido.programapdd')),
            ],
            options={
                'verbose_name': 'Sector Metodologia General Ajustada',
                'verbose_name_plural': 'Sectores Metodologia General Ajustada',
            },
        ),
        migrations.AddField(
            model_name='programamga',
            name='sector_mga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.sectormga'),
        ),
        migrations.CreateModel(
            name='SectorPDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_pdd', models.CharField(max_length=80)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('linea_estrategica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.lineaestrategica')),
            ],
            options={
                'verbose_name': 'Sector Plan de Desarrollo',
                'verbose_name_plural': 'Sectores Plan de Desarrollo',
            },
        ),
        migrations.AddField(
            model_name='programapdd',
            name='sector_pdd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.sectorpdd'),
        ),
        migrations.CreateModel(
            name='IndicadorMGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador_mga', models.CharField(max_length=80)),
                ('codigo_indicador_mga', models.CharField(max_length=9)),
                ('descripcion', models.TextField()),
                ('medido_a_traves_de', models.CharField(max_length=100)),
                ('tiene_edt', models.BooleanField()),
                ('tipo_de_acumulacion', models.CharField(choices=[('AC', 'Acumulativo'), ('NC', 'No Acumulativo')], max_length=2)),
                ('meta_cuatrienio', models.DecimalField(decimal_places=10, max_digits=30)),
                ('meta_fisica_esperada_2024', models.DecimalField(decimal_places=10, max_digits=30)),
                ('meta_fisica_esperada_2025', models.DecimalField(decimal_places=10, max_digits=30)),
                ('meta_fisica_esperada_2026', models.DecimalField(decimal_places=10, max_digits=30)),
                ('meta_fisica_esperada_2027', models.DecimalField(decimal_places=10, max_digits=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('dependencia_responsable', models.ManyToManyField(to='contenido.dependencias')),
                ('producto_mga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.productomga')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.unidadmedida')),
            ],
            options={
                'verbose_name': 'Indicador Metodologia General Ajustada',
                'verbose_name_plural': 'Indicadores Metodologia General Ajustada',
            },
        ),
        migrations.AddIndex(
            model_name='productomga',
            index=models.Index(fields=['fecha_creacion'], name='contenido_p_fecha_c_738c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='sectormga',
            index=models.Index(fields=['fecha_creacion'], name='contenido_s_fecha_c_e1a8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='programamga',
            index=models.Index(fields=['fecha_creacion'], name='contenido_p_fecha_c_41f5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='sectorpdd',
            index=models.Index(fields=['fecha_creacion'], name='contenido_s_fecha_c_94dc47_idx'),
        ),
        migrations.AddIndex(
            model_name='programapdd',
            index=models.Index(fields=['fecha_creacion'], name='contenido_p_fecha_c_f51850_idx'),
        ),
        migrations.AddIndex(
            model_name='indicadormga',
            index=models.Index(fields=['fecha_creacion'], name='contenido_i_fecha_c_a53f0c_idx'),
        ),
    ]
