# Generated by Django 5.2.11 on 2026-02-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicadormga',
            options={'verbose_name': 'Indicador MGA', 'verbose_name_plural': 'Indicadores MGA'},
        ),
        migrations.AlterModelOptions(
            name='productomga',
            options={'verbose_name': 'Producto MGA', 'verbose_name_plural': 'Productos MGA'},
        ),
        migrations.AlterModelOptions(
            name='programamga',
            options={'verbose_name': 'Programa MGA', 'verbose_name_plural': 'Programas MGA'},
        ),
        migrations.AlterModelOptions(
            name='programapdd',
            options={'verbose_name': 'Programa PDD', 'verbose_name_plural': 'Programas PDD'},
        ),
        migrations.AlterModelOptions(
            name='sectormga',
            options={'verbose_name': 'Sector MGA', 'verbose_name_plural': 'Sectores MGA'},
        ),
        migrations.AlterModelOptions(
            name='sectorpdd',
            options={'verbose_name': 'Sector PDD', 'verbose_name_plural': 'Sectores PDD'},
        ),
    ]
