# Generated by Django 5.2.11 on 2026-02-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_alter_indicadormga_options_alter_productomga_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencias',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
