# Generated by Django 5.2.11 on 2026-02-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_alter_dependencias_correo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineaestrategica',
            options={'verbose_name': '1. Linea Estrategica', 'verbose_name_plural': '2. Lineas Estrategicas'},
        ),
    ]
