# Generated by Django 5.2.11 on 2026-02-11 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_alter_lineaestrategica_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicadormga',
            options={'verbose_name': '7. Indicador MGA', 'verbose_name_plural': '7. Indicadores MGA'},
        ),
        migrations.AlterModelOptions(
            name='lineaestrategica',
            options={'verbose_name': '1. Linea Estrategica', 'verbose_name_plural': '1. Lineas Estrategicas'},
        ),
        migrations.AlterModelOptions(
            name='productomga',
            options={'verbose_name': '6. Producto MGA', 'verbose_name_plural': '6. Productos MGA'},
        ),
        migrations.AlterModelOptions(
            name='programamga',
            options={'verbose_name': '5. Programa MGA', 'verbose_name_plural': '5. Programas MGA'},
        ),
        migrations.AlterModelOptions(
            name='programapdd',
            options={'verbose_name': '3. Programa PDD', 'verbose_name_plural': '3. Programas PDD'},
        ),
        migrations.AlterModelOptions(
            name='sectormga',
            options={'verbose_name': '4. Sector MGA', 'verbose_name_plural': '4. Sectores MGA'},
        ),
        migrations.AlterModelOptions(
            name='sectorpdd',
            options={'verbose_name': '2. Sector PDD', 'verbose_name_plural': '2. Sectores PDD'},
        ),
    ]
